add ci-success gatekeeper job to simplify required checks

diff --git a/.github/workflows/build-and-test.yml b/.github/workflows/build-and-test.yml
--- a/.github/workflows/build-and-test.yml
+++ b/.github/workflows/build-and-test.yml
@@ -219,3 +219,20 @@ jobs:
         shell: 'bash'
         run: |
           go run github.com/google/addlicense@v1.1.1 -check -s=only .
+
+  # Add a gatekeeper job to act as the (main) required check, which in turn depends on all other required jobs.
+  # This makes the required check management in GitHub settings tractable, as we don't have to tweak the settings everytime
+  # a job name changes or a matrix option is modified.
+  ci-success:
+    runs-on: ubuntu-latest
+    if: always()
+    # Specify all top-level jobs that are required to pass.
+    needs: [build, lint-code, lint-license]
+    steps:
+      - name: Check overall status
+        run: |
+          if [[ "${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }}" == "true" ]]; then
+            echo "One or more dependent jobs failed or were cancelled."
+            exit 1
+          fi
+          echo "All required jobs passed!"
